baseurl                  = "https://example.com"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "WorkSpace"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"
relativeURLs             = true
publishDir               = "docs"                           # for github pages


[params]
    dateform             = "15:04.02.01.06"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "Init"
    footerText           = "WorkSpace &larr; A Story of Work"
    showDate             = true

# Metadata for Open Graph and Twitter
    description          = "WorkSpace &larr; A Story of Work"
    images               = ["tn.png"]
    title                = "WorkSpace &larr; A Story of Work"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/2429862923_01ba069d5f_b.jpg"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional


[[params.mainMenu]]
    link = "visitors-guide"
    text = "A Visitors Guide"

[[params.mainMenu]]
    link = "posts"
    text = "Posts"

[[params.mainMenu]]
    link = "chapters/"
    text = "Chapters"

[[params.mainMenu]]
    link = "categories"
    text = "Categories"

[[params.mainMenu]]
    link = "gallery"
    text = "Gallery"


[imaging]
    quality = 75
